#!/usr/bin/env python3
"""
Documentation MCP — Docs as Code (Google pattern)

Industry pattern: "Docs as Code" (Software Engineering at Google)
  - Documentation lives in the repo, version controlled
  - Generated FROM code, not manually written
  - Never goes stale because it's auto-generated

Generates 5 types of documentation:
  1. README       — project overview, install, run, structure
  2. Changelog    — from git log + task board (Keep a Changelog format)
  3. API docs     — from scanning API route files
  4. Env docs     — from scanning .env.example + code usage
  5. Onboarding   — pulls from ALL sources for new developer/session

All generated docs go to .webforge/docs/ for review.
Developer merges manually (option C — safest, Google's review pattern).
"""

import os
import sys
import json
import subprocess
import re
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).parent))
from common import write_log, success, fail, utc_now, McpResult, get_project_root
from memory import session_append, read_rules, list_adrs, list_rules


def info() -> dict:
    return {
        "id": "m-docs",
        "name": "Documentation MCP",
        "tier": 3,
        "owner": "Thoth",
        "job": "Generate README, changelog, API docs, env docs, onboarding from project state. Docs as Code.",
    }


# ── Paths ──
def docs_output_dir() -> Path:
    d = get_project_root() / ".webforge" / "docs"
    d.mkdir(parents=True, exist_ok=True)
    return d


# ── Helpers ──
def read_package_json() -> dict:
    pkg_path = get_project_root() / "package.json"
    if not pkg_path.exists():
        return {}
    try:
        return json.loads(pkg_path.read_text())
    except Exception as _e:
        write_log("Docs", "Thoth", "parse package.json", {"error": str(_e)})
        return {}


def get_git_log(limit: int = 20) -> list:
    project = get_project_root()
    try:
        result = subprocess.run(
            ["git", "log", f"-{limit}", "--pretty=format:%H|%s|%an|%ad"],
            cwd=str(project), capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return []
        logs = []
        for line in result.stdout.strip().split("\n"):
            parts = line.split("|", 3)
            if len(parts) == 4:
                logs.append({
                    "hash": parts[0][:8],
                    "message": parts[1],
                    "author": parts[2],
                    "date": parts[3],
                })
        return logs
    except Exception as _e:
        write_log("Docs", "Thoth", "get git log", {"error": str(_e)})
        return []


def count_files() -> dict:
    project = get_project_root()
    src = project / "src"
    stats = {"tsx": 0, "ts": 0, "test": 0, "total": 0}
    if src.exists():
        stats["tsx"] = len(list(src.rglob("*.tsx")))
        stats["ts"] = len(list(src.rglob("*.ts")))
        stats["test"] = len(list(src.rglob("*.test.*"))) + len(list(src.rglob("*.spec.*")))
    all_files = [f for f in project.rglob("*") if f.is_file()
                 and ".git" not in str(f) and "node_modules" not in str(f)
                 and ".next" not in str(f) and ".webforge" not in str(f)]
    stats["total"] = len(all_files)
    return stats


# ── 1. README ──
def readme_generate() -> McpResult:
    """Generate README from project state."""
    project = get_project_root()
    pkg = read_package_json()
    name = pkg.get("name", project.name)
    scripts = pkg.get("scripts", {})
    deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
    stats = count_files()

    # Detect key dependencies
    key_deps = []
    dep_names = {
        "next": "Next.js",
        "react": "React",
        "typescript": "TypeScript",
        "tailwindcss": "Tailwind CSS",
        "@supabase/supabase-js": "Supabase",
        "@sentry/nextjs": "Sentry",
        "prisma": "Prisma",
        "vitest": "Vitest",
        "@playwright/test": "Playwright",
        "react-hook-form": "React Hook Form",
        "zustand": "Zustand",
        "zod": "Zod",
        "framer-motion": "Framer Motion",
    }
    for dep, label in dep_names.items():
        if dep in deps:
            key_deps.append(f"{label} `{deps[dep]}`")

    # Get ADRs
    adrs_result = list_adrs()
    adrs = adrs_result.data.get("adrs", [])

    # Get rules
    rules_text = read_rules()

    content = f"""# {name}

> Auto-generated by WebForge on {utc_now()[:10]}
> Review and merge into your README manually.

## Description

{pkg.get("description", "(Add a description to package.json)")}

## Tech Stack

{chr(10).join(f"- {d}" for d in key_deps) if key_deps else "- (no dependencies detected)"}

## Quick Start

```bash
# Install dependencies
npm install

# Set up environment
cp .env.example .env.local
# Edit .env.local with your values

# Run development server
{scripts.get("dev", "npm run dev")}

# Build for production
{scripts.get("build", "npm run build")}

# Start production server
{scripts.get("start", "npm start")}
```

## Available Scripts

| Script | Command | Description |
|--------|---------|-------------|
"""
    for script_name, script_cmd in scripts.items():
        content += f"| `{script_name}` | `npm run {script_name}` | {script_cmd} |\n"

    content += f"""
## Project Structure

- **Total files:** {stats['total']}
- **Components:** {stats['tsx']} .tsx files
- **Modules:** {stats['ts']} .ts files
- **Tests:** {stats['test']} test files

```
{project.name}/
├── src/
│   ├── app/           # Next.js App Router pages
│   ├── components/    # React components
│   ├── lib/           # Utilities, hooks, actions
│   └── ...
├── public/            # Static assets
├── package.json
└── ...
```

## Architecture Decisions

"""
    if adrs:
        for adr in adrs:
            content += f"- {adr['file']}: {adr['title']}\n"
    else:
        content += "(No ADRs yet. Use /add-adr to document decisions.)\n"

    content += f"""
## Rules (Do's and Don'ts)

"""
    if rules_text and rules_text != "(no rules set)":
        content += rules_text + "\n"
    else:
        content += "(No rules set. Use /add-rule or /correct to add rules.)\n"

    content += f"""
## Testing

```bash
# Run unit tests
{scripts.get("test", "npm test")}

# Run E2E tests
{scripts.get("e2e", "npm run e2e")}

# Run linter
{scripts.get("lint", "npm run lint")}
```

## Documentation

- **Session logs:** `.webforge/memory/` — what we did, where we stopped
- **Rules:** `.webforge/rules/` — do's and don'ts
- **ADRs:** `docs/adr/` — architecture decisions
- **RFCs:** `.webforge/rfcs/` — design proposals for one-way door tasks
- **Knowledge:** `.webforge/knowledge/` — research findings
- **Tasks:** `.webforge/tasks/` — Kanban board

---
*Generated by WebForge Documentation MCP on {utc_now()}*
"""

    output = docs_output_dir() / "README.generated.md"
    output.write_text(content, encoding="utf-8")

    session_append("DOC GENERATED — README", agent="Thoth", kind="note")
    return success({
        "file": str(output),
        "lines": content.count("\n"),
        "message": f"README generated → {output}\nReview and merge into your project's README.md",
    })


# ── 2. Changelog ──
def changelog_generate() -> McpResult:
    """Generate changelog from git log + task board (Keep a Changelog format)."""
    logs = get_git_log(50)

    # Categorize commits using conventional commit format
    categories = {
        "Added": [],
        "Changed": [],
        "Deprecated": [],
        "Removed": [],
        "Fixed": [],
        "Security": [],
    }

    commit_map = {
        "feat": "Added",
        "add": "Added",
        "change": "Changed",
        "refactor": "Changed",
        "update": "Changed",
        "deprecate": "Deprecated",
        "remove": "Removed",
        "delete": "Removed",
        "fix": "Fixed",
        "bugfix": "Fixed",
        "hotfix": "Fixed",
        "security": "Security",
    }

    for log in logs:
        msg = log["message"].lower()
        categorized = False
        for prefix, category in commit_map.items():
            if msg.startswith(prefix + ":") or msg.startswith(prefix + "("):
                categories[category].append(log)
                categorized = True
                break
        if not categorized:
            # Try to guess from message content
            if "fix" in msg or "bug" in msg:
                categories["Fixed"].append(log)
            elif "add" in msg or "new" in msg or "create" in msg:
                categories["Added"].append(log)
            elif "change" in msg or "update" in msg or "refactor" in msg:
                categories["Changed"].append(log)
            elif "remove" in msg or "delete" in msg:
                categories["Removed"].append(log)
            else:
                categories["Changed"].append(log)

    content = """# Changelog

> Auto-generated by WebForge from git history.
> Format: [Keep a Changelog](https://keepachangelog.com/)

## [Unreleased]

"""
    for category, entries in categories.items():
        if entries:
            content += f"### {category}\n"
            for e in entries:
                content += f"- {e['message']} ({e['hash']})\n"
            content += "\n"

    content += f"""
---
*Generated by WebForge Documentation MCP on {utc_now()}*
*Based on last {len(logs)} commits.*
"""

    output = docs_output_dir() / "CHANGELOG.generated.md"
    output.write_text(content, encoding="utf-8")

    session_append("DOC GENERATED — Changelog", agent="Thoth", kind="note")
    return success({
        "file": str(output),
        "commits_analyzed": len(logs),
        "message": f"Changelog generated → {output}\n{len(logs)} commits analyzed.",
    })


# ── 3. API Documentation ──
def api_docs_generate() -> McpResult:
    """Generate API docs from scanning route files."""
    project = get_project_root()
    api_dir = project / "src" / "app" / "api"

    if not api_dir.exists():
        return fail("No API directory found (src/app/api/). This project may not have API routes.")

    routes = []
    for route_file in sorted(api_dir.rglob("route.ts")):
        rel_path = route_file.relative_to(project)
        # Extract route path from file path
        route_path = str(rel_path).replace("src/app/api", "").replace("/route.ts", "")
        if not route_path:
            route_path = "/"

        # Read the file to find HTTP methods and descriptions
        content = route_file.read_text(encoding="utf-8")

        methods = []
        for method in ["GET", "POST", "PUT", "PATCH", "DELETE"]:
            if f"export async function {method.lower()}" in content or f"export function {method.lower()}" in content:
                methods.append(method)

        # Try to find comments/descriptions
        desc_match = re.search(r'/\*\*(.*?)\*/', content, re.DOTALL)
        description = ""
        if desc_match:
            desc_lines = desc_match.group(1).strip().split("\n")
            description = " ".join(l.strip().lstrip("* ").strip() for l in desc_lines if l.strip() and not l.strip().startswith("@"))

        routes.append({
            "path": route_path,
            "file": str(rel_path),
            "methods": methods,
            "description": description.strip() or "(no description — add JSDoc comment)",
        })

    # Generate markdown
    content = """# API Documentation

> Auto-generated by WebForge from route files.
> Add JSDoc comments to your route files for better descriptions.

"""
    for r in routes:
        methods_str = " ".join(f"`{m}`" for m in r["methods"]) if r["methods"] else "(no methods exported)"
        content += f"## {methods_str} `{r['path']}`\n\n"
        content += f"**File:** `{r['file']}`\n\n"
        content += f"**Description:** {r['description']}\n\n"
        content += "---\n\n"

    content += f"\n*Generated by WebForge Documentation MCP on {utc_now()}*\n"
    content += f"*{len(routes)} routes found.*\n"

    output = docs_output_dir() / "API_DOCS.generated.md"
    output.write_text(content, encoding="utf-8")

    session_append(f"DOC GENERATED — API docs ({len(routes)} routes)", agent="Thoth", kind="note")
    return success({
        "file": str(output),
        "routes": len(routes),
        "message": f"API docs generated → {output}\n{len(routes)} routes documented.",
    })


# ── 4. Environment Documentation ──
def env_docs_generate() -> McpResult:
    """Document environment variables from .env.example + code usage."""
    project = get_project_root()
    env_example = project / ".env.example"

    if not env_example.exists():
        return fail("No .env.example file found. Create one first.")

    lines = env_example.read_text(encoding="utf-8").split("\n")

    vars_doc = []
    current_comment = ""

    for line in lines:
        line = line.strip()
        if not line:
            current_comment = ""
            continue
        if line.startswith("#"):
            current_comment = line.lstrip("# ").strip()
            continue
        if "=" in line:
            parts = line.split("=", 1)
            var_name = parts[0].strip()
            var_value = parts[1].strip() if len(parts) > 1 else ""

            # Determine if it's required
            is_required = not var_value or var_value == ""

            # Check if it's a public var (exposed to client)
            is_public = var_name.startswith("NEXT_PUBLIC_")

            vars_doc.append({
                "name": var_name,
                "example": var_value if var_value else "(required — no default)",
                "required": is_required,
                "public": is_public,
                "comment": current_comment,
            })
            current_comment = ""

    # Generate markdown
    content = """# Environment Variables

> Auto-generated by WebForge from .env.example

"""
    content += "| Variable | Required | Public | Description |\n"
    content += "|----------|----------|--------|-------------|\n"

    for v in vars_doc:
        req = "✅ yes" if v["required"] else "no"
        pub = "⚠️ yes" if v["public"] else "no"
        desc = v["comment"] or v["example"]
        content += f"| `{v['name']}` | {req} | {pub} | {desc} |\n"

    content += f"""
## Notes

- **Public** variables (NEXT_PUBLIC_*) are exposed to the browser. Never put secrets in them.
- **Required** variables must be set before the app will run.
- Copy `.env.example` to `.env.local` and fill in your values.

---
*Generated by WebForge Documentation MCP on {utc_now()}*
*{len(vars_doc)} variables found.*
"""

    output = docs_output_dir() / "ENV_DOCS.generated.md"
    output.write_text(content, encoding="utf-8")

    session_append(f"DOC GENERATED — Env docs ({len(vars_doc)} vars)", agent="Thoth", kind="note")
    return success({
        "file": str(output),
        "vars": len(vars_doc),
        "message": f"Env docs generated → {output}\n{len(vars_doc)} variables documented.",
    })


# ── 5. Onboarding ──
def onboard_generate() -> McpResult:
    """Generate onboarding document pulling from ALL sources."""
    project = get_project_root()
    pkg = read_package_json()
    name = pkg.get("name", project.name)
    scripts = pkg.get("scripts", {})
    stats = count_files()

    # Get ADRs
    adrs_result = list_adrs()
    adrs = adrs_result.data.get("adrs", [])

    # Get rules
    rules_text = read_rules()

    # Get git log
    logs = get_git_log(5)

    # Load task board
    tasks_summary = ""
    try:
        from task import load_board
        board = load_board()
        tasks = board.get("tasks", [])
        doing = [t for t in tasks if t["status"] == "doing"]
        todo = [t for t in tasks if t["status"] == "todo"]
        backlog = [t for t in tasks if t["status"] == "backlog"]
        done = [t for t in tasks if t["status"] == "done"]

        tasks_summary = f"""
## Current Tasks

| Column | Count |
|--------|-------|
| Backlog | {len(backlog)} |
| TODO | {len(todo)} |
| DOING | {len(doing)} |
| DONE | {len(done)} |

"""
        if doing:
            tasks_summary += "### In Progress\n"
            for t in doing:
                tasks_summary += f"- {t['id']}: {t['title']} (owner: {t.get('owner', 'unassigned')})\n"
        if todo:
            tasks_summary += "\n### Up Next\n"
            for t in todo:
                tasks_summary += f"- {t['id']}: {t['title']}\n"
    except Exception as _e:
        write_log("Docs", "Thoth", "load task board", {"error": str(_e)})
        tasks_summary = "(Task board not available)"

    content = f"""# {name} — Developer Onboarding

> Auto-generated by WebForge on {utc_now()[:10]}
> This document helps new developers (or new AI sessions) understand the project quickly.

## Quick Start

```bash
# 1. Install dependencies
npm install

# 2. Set up environment
cp .env.example .env.local
# Edit .env.local — see /env-docs for what each variable does

# 3. Run development server
{scripts.get("dev", "npm run dev")}

# 4. Run tests
{scripts.get("test", "npm test")}

# 5. Run linter
{scripts.get("lint", "npm run lint")}
```

## Project Overview

- **Name:** {name}
- **Description:** {pkg.get("description", "(none)")}
- **Total files:** {stats['total']}
- **Components:** {stats['tsx']} .tsx
- **Modules:** {stats['ts']} .ts
- **Tests:** {stats['test']} test files

## Tech Stack

"""
    deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
    dep_names = {
        "next": "Next.js", "react": "React", "typescript": "TypeScript",
        "tailwindcss": "Tailwind CSS", "@supabase/supabase-js": "Supabase",
        "@sentry/nextjs": "Sentry", "prisma": "Prisma", "vitest": "Vitest",
        "@playwright/test": "Playwright", "react-hook-form": "React Hook Form",
        "zustand": "Zustand", "zod": "Zod", "framer-motion": "Framer Motion",
    }
    for dep, label in dep_names.items():
        if dep in deps:
            content += f"- {label} `{deps[dep]}`\n"

    content += f"""
## Available Scripts

"""
    for script_name in scripts:
        content += f"- `npm run {script_name}`\n"

    content += f"""
## Architecture Decisions (ADRs)

"""
    if adrs:
        for adr in adrs:
            content += f"- {adr['file']}: {adr['title']}\n"
    else:
        content += "(No ADRs yet)\n"

    content += f"""
## Rules (Do's and Don'ts)

{rules_text if rules_text != "(no rules set)" else "(No rules set yet)"}

{tasks_summary}

## Recent Commits

"""
    for log in logs:
        content += f"- {log['hash']}: {log['message']}\n"

    content += f"""
## WebForge

This project uses WebForge for AI-assisted development.

### At the start of each session:
```
/resume    ← Read all memory, continue where you stopped
```

### To work on a task:
```
/build     ← Proposes next task, you approve
/task-done ← Mark task done (runs quality checks)
```

### To report a bug:
```
/bug "description" severity
```

### To save a correction as a rule:
```
/correct "what was wrong" | "what to do instead"
```

### To end a session:
```
/stop "What I was working on. What's next."
```

---
*Generated by WebForge Documentation MCP on {utc_now()}*
"""

    output = docs_output_dir() / "ONBOARDING.generated.md"
    output.write_text(content, encoding="utf-8")

    session_append("DOC GENERATED — Onboarding", agent="Thoth", kind="note")
    return success({
        "file": str(output),
        "lines": content.count("\n"),
        "message": f"Onboarding doc generated → {output}\nRead it to understand the project quickly.",
    })


# ── Generate all ──
def generate_all() -> McpResult:
    """Generate all 5 documentation types at once."""
    results = []

    print("Generating README...")
    r = readme_generate()
    results.append(("README", r))

    print("Generating Changelog...")
    r = changelog_generate()
    results.append(("Changelog", r))

    print("Generating API docs...")
    r = api_docs_generate()
    results.append(("API Docs", r))

    print("Generating Env docs...")
    r = env_docs_generate()
    results.append(("Env Docs", r))

    print("Generating Onboarding...")
    r = onboard_generate()
    results.append(("Onboarding", r))

    output_dir = docs_output_dir()
    lines = []
    lines.append("=" * 60)
    lines.append("DOCUMENTATION GENERATED")
    lines.append("=" * 60)
    lines.append(f"\nOutput directory: {output_dir}\n")

    for name, result in results:
        if result.ok:
            lines.append(f"  ✓ {name:15s} → {result.data.get('file', '').split('/')[-1]}")
        else:
            lines.append(f"  ✗ {name:15s} → {result.error}")

    lines.append("\nReview the generated files and merge into your project docs.")
    lines.append("Generated docs are in .webforge/docs/ (not tracked by git).")

    return success({"output": "\n".join(lines), "results": [(n, r.ok) for n, r in results]})


# ── CLI ──
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Documentation MCP — Docs as Code")
        print("Usage: python docs.py <command>")
        print()
        print("Commands:")
        print("  readme      Generate README from project state")
        print("  changelog   Generate changelog from git history")
        print("  api-docs    Generate API documentation from route files")
        print("  env-docs    Document environment variables")
        print("  onboard     Generate onboarding document")
        print("  all         Generate all 5 at once")
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "info":
        print(json.dumps(info(), indent=2))
    elif cmd == "readme":
        result = readme_generate()
        print(result.data.get("message", result.to_dict()))
    elif cmd == "changelog":
        result = changelog_generate()
        print(result.data.get("message", result.to_dict()))
    elif cmd == "api-docs":
        result = api_docs_generate()
        print(result.data.get("message", result.to_dict()))
    elif cmd == "env-docs":
        result = env_docs_generate()
        print(result.data.get("message", result.to_dict()))
    elif cmd == "onboard":
        result = onboard_generate()
        print(result.data.get("message", result.to_dict()))
    elif cmd == "all":
        result = generate_all()
        print(result.data["output"])
    else:
        print(f"Unknown command: {cmd}")
