#!/usr/bin/env python3
"""
Ceo Agent — Executive Department
Auto-generated by WebForge agent generator.

THE BODY: This script IS Ceo. It controls what the AI does.
THE BRAIN: The AI only reasons when Ceo asks it to.

Skill file: skills/executive/ceo.md
"""

import sys
import os
import json
from pathlib import Path

WEBFORGE_HOME = Path.home() / "webforge"
sys.path.insert(0, str(WEBFORGE_HOME / "agents"))
sys.path.insert(0, str(WEBFORGE_HOME / "mcp"))

from base import Agent


class Ceo(Agent):
    """Auto-generated agent script for Ceo."""

    name = "Ceo"
    department = "Executive"
    skill_file = "executive/ceo.md"
    reports_to = None
    can_route_to = ["Hephaestus", "Athena", "Minos", "Thoth", "Daedalus", "Voss"]

    allowed_actions = ["create_bugfix_task", "create_feature_task", "run_standup", "answer_question", "route", "respond"]
    forbidden_actions = ["write_code", "research", "generate_docs", "run_quality_check", "review_code", "learn"]

    # Per-agent correction rules (Daedalus patches these)
    correction_rules = []

    def execute(self, action, data, context):
        """Execute the action. CODE, not AI."""
        if action == "answer_question":
            return {
                "agent": self.name,
                "action": action,
                "message": f"I am {self.name} ({self.department}). I'm ready to work.",
                "next_step": None,
            }
        elif action == "route":
            return self._route_to(data.get("target", "Hermes"), data.get("message", ""))
        return {
            "agent": self.name,
            "action": action,
            "message": f"I am {self.name}. Action: {action}",
            "next_step": None,
        }


def run(message, context=None):
    """Called when developer talks to Ceo."""
    agent = Ceo()
    return agent.run(message, context)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Ceo Agent — Executive")
        print("Usage: python ceo.py <message>")
        sys.exit(1)
    message = " ".join(sys.argv[1:])
    result = run(message)
    print(result.get("message", json.dumps(result, indent=2)))
