#!/usr/bin/env python3
"""
JanusMoss Agent — Quality Department
Auto-generated by WebForge agent generator.

THE BODY: This script IS JanusMoss. It controls what the AI does.
THE BRAIN: The AI only reasons when JanusMoss asks it to.

Skill file: skills/quality/janus-moss.md
"""

import sys
import os
import json
from pathlib import Path

WEBFORGE_HOME = Path.home() / "webforge"
sys.path.insert(0, str(WEBFORGE_HOME / "agents"))
sys.path.insert(0, str(WEBFORGE_HOME / "mcp"))

from base import Agent


class JanusMoss(Agent):
    """Auto-generated agent script for JanusMoss."""

    name = "JanusMoss"
    department = "Quality"
    skill_file = "quality/janus-moss.md"
    reports_to = "Minos"
    can_route_to = ["Minos", "Hermes", "Hephaestus"]

    allowed_actions = ["run_quality_check", "review_code", "answer_question", "route", "respond"]
    forbidden_actions = ["write_code", "create_bugfix_task", "create_feature_task", "run_standup", "research", "generate_docs", "learn"]

    # Per-agent correction rules (Daedalus patches these)
    correction_rules = []

    def execute(self, action, data, context):
        """Execute the action. CODE, not AI."""
        if action == "answer_question":
            return {
                "agent": self.name,
                "action": action,
                "message": f"I am {self.name} ({self.department}). I'm ready to work.",
                "next_step": None,
            }
        elif action == "route":
            return self._route_to(data.get("target", "Hermes"), data.get("message", ""))
        return {
            "agent": self.name,
            "action": action,
            "message": f"I am {self.name}. Action: {action}",
            "next_step": None,
        }


def run(message, context=None):
    """Called when developer talks to JanusMoss."""
    agent = JanusMoss()
    return agent.run(message, context)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("JanusMoss Agent — Quality")
        print("Usage: python janus-moss.py <message>")
        sys.exit(1)
    message = " ".join(sys.argv[1:])
    result = run(message)
    print(result.get("message", json.dumps(result, indent=2)))
