#!/usr/bin/env python3
"""
OdinGlade Agent — Intelligence Department
Auto-generated by WebForge agent generator.

THE BODY: This script IS OdinGlade. It controls what the AI does.
THE BRAIN: The AI only reasons when OdinGlade asks it to.

Skill file: skills/intelligence/odin-glade.md
"""

import sys
import os
import json
from pathlib import Path

WEBFORGE_HOME = Path.home() / "webforge"
sys.path.insert(0, str(WEBFORGE_HOME / "agents"))
sys.path.insert(0, str(WEBFORGE_HOME / "mcp"))

from base import Agent


class OdinGlade(Agent):
    """Auto-generated agent script for OdinGlade."""

    name = "OdinGlade"
    department = "Intelligence"
    skill_file = "intelligence/odin-glade.md"
    reports_to = "Athena"
    can_route_to = ["Athena", "Hermes"]

    allowed_actions = ["research", "answer_question", "route", "respond"]
    forbidden_actions = ["write_code", "create_bugfix_task", "create_feature_task", "run_standup", "generate_docs", "run_quality_check", "review_code", "learn"]

    # Per-agent correction rules (Daedalus patches these)
    correction_rules = []

    def execute(self, action, data, context):
        """Execute the action. CODE, not AI."""
        if action == "answer_question":
            return {
                "agent": self.name,
                "action": action,
                "message": f"I am {self.name} ({self.department}). I'm ready to work.",
                "next_step": None,
            }
        elif action == "route":
            return self._route_to(data.get("target", "Hermes"), data.get("message", ""))
        return {
            "agent": self.name,
            "action": action,
            "message": f"I am {self.name}. Action: {action}",
            "next_step": None,
        }


def run(message, context=None):
    """Called when developer talks to OdinGlade."""
    agent = OdinGlade()
    return agent.run(message, context)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("OdinGlade Agent — Intelligence")
        print("Usage: python odin-glade.py <message>")
        sys.exit(1)
    message = " ".join(sys.argv[1:])
    result = run(message)
    print(result.get("message", json.dumps(result, indent=2)))
